// ctx.js — shared context + decoupling buses for Dragon Flight 3D.
//
// CONTRACT (do not break — workers depend on this; do not edit this file in a worker):
//   Every module is `export default { id, init(ctx), update(dt, ctx), dispose?() }`.
//   Modules talk ONLY to `ctx`, never import each other.
//
// Buses are no-op-safe so the game runs even when a module is an unimplemented stub.
// A provider module REPLACES the bus method in its init (e.g. fx.js sets ctx.fx.spawn);
// consumer modules just call the method.

import * as THREE from 'three';

// Deterministic PRNG (mulberry32) so the world is identical every load.
function makeRng(seed) {
  let a = seed >>> 0;
  return function () {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Tiny pub/sub.
function makeEvents() {
  const map = new Map();
  return {
    on(name, fn) {
      if (!map.has(name)) map.set(name, new Set());
      map.get(name).add(fn);
      return () => map.get(name)?.delete(fn);
    },
    emit(name, payload) {
      const set = map.get(name);
      if (!set) return;
      for (const fn of set) {
        try { fn(payload); } catch (e) { console.error(`[events] ${name} handler failed`, e); }
      }
    },
  };
}

/**
 * Build the shared context.
 * @param {{scene:THREE.Scene, camera:THREE.PerspectiveCamera, renderer:THREE.WebGLRenderer, clock:THREE.Clock}} core
 */
export function createCtx(core) {
  // ----- The objective location (castle sits here; controls/compass/minimap read it). -----
  const OBJECTIVE = new THREE.Vector3(0, 60, -900);

  // ----- Player root (the dragon). controls.js writes its transform; dragon/camera read it. -----
  const playerGroup = new THREE.Group();
  playerGroup.name = 'player';
  playerGroup.position.set(0, 120, 600);
  core.scene.add(playerGroup);

  const _forward = new THREE.Vector3();
  const player = {
    group: playerGroup,
    velocity: new THREE.Vector3(0, 0, 0),
    // World-space forward (-Z is forward in three.js convention).
    getForward(out = _forward) {
      return out.set(0, 0, -1).applyQuaternion(playerGroup.quaternion).normalize();
    },
  };

  // ----- Shared mutable game state (HUD/compass/minimap/quest read; controls/combat write). -----
  const state = {
    hp: 100, hpMax: 100,
    mp: 100, mpMax: 100,
    speed: 0,            // current forward speed (units/s)
    alt: playerGroup.position.y,
    heading: 0,          // radians, 0 = north (-Z)
    distanceKm: 0,       // distance to objective, in "km" display units
    score: 0,
    phase: 'title',      // 'title' | 'playing' | 'win' | 'lose'  (screens.js owns transitions)
  };

  // ----- Input. Listeners attached here; modules read flags/sets. -----
  const input = {
    keys: new Set(),
    pointer: { dx: 0, dy: 0, locked: false },
    accel: false,        // Shift
    descend: false,      // Ctrl
    isDown(code) { return this.keys.has(code); },
    _consumePointer() { const d = { dx: this.pointer.dx, dy: this.pointer.dy }; this.pointer.dx = 0; this.pointer.dy = 0; return d; },
  };
  function onKey(e, down) {
    // Don't hijack devtools / reload shortcuts.
    if (e.metaKey || (e.ctrlKey && e.code !== 'ControlLeft' && e.code !== 'ControlRight')) return;
    if (down) input.keys.add(e.code); else input.keys.delete(e.code);
    input.accel = input.keys.has('ShiftLeft') || input.keys.has('ShiftRight');
    input.descend = input.keys.has('ControlLeft') || input.keys.has('ControlRight');
    if (['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Space'].includes(e.code)) e.preventDefault();
  }
  window.addEventListener('keydown', (e) => onKey(e, true));
  window.addEventListener('keyup', (e) => onKey(e, false));
  window.addEventListener('blur', () => { input.keys.clear(); input.accel = false; input.descend = false; });
  const canvas = core.renderer.domElement;
  canvas.addEventListener('mousemove', (e) => {
    if (input.pointer.locked) { input.pointer.dx += e.movementX; input.pointer.dy += e.movementY; }
  });
  document.addEventListener('pointerlockchange', () => {
    input.pointer.locked = document.pointerLockElement === canvas;
  });
  canvas.addEventListener('click', () => { if (state.phase === 'playing') canvas.requestPointerLock?.(); });

  // ----- World registry: things plotted on the minimap. -----
  const world = {
    blips: [],   // { object3d, color, type }
    rng: makeRng(0xC0FFEE),
    OBJECTIVE,
    registerBlip(object3d, opts = {}) {
      const blip = { object3d, color: opts.color || '#ffffff', type: opts.type || 'poi' };
      this.blips.push(blip);
      return blip;
    },
    removeBlip(object3d) {
      const i = this.blips.findIndex((b) => b.object3d === object3d);
      if (i >= 0) this.blips.splice(i, 1);
    },
  };

  // ----- Combat bus: fire-breath/abilities call damageAt; enemies registerTarget. -----
  const combat = {
    targets: [],   // { object3d, hp, hpMax, radius, onDeath, onHit }
    registerTarget(object3d, opts = {}) {
      const t = {
        object3d,
        hp: opts.hp ?? 10, hpMax: opts.hp ?? 10,
        radius: opts.radius ?? 6,
        onDeath: opts.onDeath || (() => {}),
        onHit: opts.onHit || (() => {}),
        alive: true,
      };
      combat.targets.push(t);
      return t;
    },
    unregisterTarget(object3d) {
      const i = combat.targets.findIndex((t) => t.object3d === object3d);
      if (i >= 0) combat.targets.splice(i, 1);
    },
    // Damage every alive target whose center is within (radius + target.radius) of pos.
    damageAt(pos, radius, amount) {
      let hits = 0;
      for (const t of combat.targets) {
        if (!t.alive || !t.object3d) continue;
        const tp = t.object3d.getWorldPosition(new THREE.Vector3());
        if (tp.distanceTo(pos) <= radius + t.radius) {
          t.hp -= amount; hits++;
          try { t.onHit(amount, pos); } catch (e) { console.error(e); }
          ctx.fx.spawn('hit', tp);
          if (t.hp <= 0 && t.alive) {
            t.alive = false;
            ctx.fx.spawn('explosion', tp);
            ctx.audio.play('explode');
            try { t.onDeath(); } catch (e) { console.error(e); }
            combat.unregisterTarget(t.object3d);
            state.score += 100;
            ctx.events.emit('enemyKilled', t);
          }
        }
      }
      return hits;
    },
  };

  // ----- FX bus: fx.js replaces spawn(); everyone else calls it. -----
  const fx = {
    spawn(/* type, position, opts */) { /* no-op until fx.js overrides */ },
  };

  // ----- Audio bus: audio.js replaces play(); everyone else calls it. -----
  const audio = {
    play(/* name, opts */) { /* no-op until audio.js overrides */ },
    setListener(/* obj3d */) {},
  };

  const ctx = {
    THREE,
    scene: core.scene,
    camera: core.camera,
    renderer: core.renderer,
    clock: core.clock,
    state,
    player,
    input,
    world,
    combat,
    fx,
    audio,
    events: makeEvents(),
    OBJECTIVE,
  };
  return ctx;
}
