// main.js — boots Three.js, builds ctx, wires every module, runs the render loop.
// DO NOT edit this file in a worker. Workers only fill in their own module under js/modules/.

import * as THREE from 'three';
import { createCtx } from './ctx.js';

// --- Module registry. Order matters for init (providers before consumers). ---
import sky from './modules/sky.js';
import clouds from './modules/clouds.js';
import terrain from './modules/terrain.js';
import water from './modules/water.js';
import islands from './modules/islands.js';
import castle from './modules/castle.js';
import ruins from './modules/ruins.js';
import dragon from './modules/dragon.js';
import wings from './modules/wings.js';
import controls from './modules/controls.js';
import camera from './modules/camera.js';
import firebreath from './modules/firebreath.js';
import abilities from './modules/abilities.js';
import hud from './modules/hud.js';
import compass from './modules/compass.js';
import minimap from './modules/minimap.js';
import quest from './modules/quest.js';
import enemies from './modules/enemies.js';
import fx from './modules/fx.js';
import audio from './modules/audio.js';
import screens from './modules/screens.js';

// Providers (fx, audio) init first so their buses exist before consumers' init.
const MODULES = [
  fx, audio,
  sky, clouds, terrain, water, islands, castle, ruins,
  dragon, wings, controls, camera,
  firebreath, abilities,
  hud, compass, minimap, quest,
  enemies,
  screens,
];

function boot() {
  const canvas = document.getElementById('game-canvas');
  const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
  renderer.setSize(window.innerWidth, window.innerHeight);
  renderer.outputColorSpace = THREE.SRGBColorSpace;

  const scene = new THREE.Scene();
  const camera3d = new THREE.PerspectiveCamera(70, window.innerWidth / window.innerHeight, 0.5, 8000);
  camera3d.position.set(0, 130, 640);
  const clock = new THREE.Clock();

  const ctx = createCtx({ scene, camera: camera3d, renderer, clock });

  window.addEventListener('resize', () => {
    camera3d.aspect = window.innerWidth / window.innerHeight;
    camera3d.updateProjectionMatrix();
    renderer.setSize(window.innerWidth, window.innerHeight);
    ctx.events.emit('resize', { w: window.innerWidth, h: window.innerHeight });
  });

  // Init every module; a failure in one must not stop the others.
  for (const m of MODULES) {
    try { m.init?.(ctx); }
    catch (e) { console.error(`[init:${m?.id || '?'}]`, e); }
  }

  let lastErr = 0;
  function frame() {
    const dt = Math.min(ctx.clock.getDelta(), 0.05); // clamp huge dt after tab switch
    for (const m of MODULES) {
      try { m.update?.(dt, ctx); }
      catch (e) {
        // Throttle spam but keep the loop alive.
        if (performance.now() - lastErr > 1000) { console.error(`[update:${m?.id || '?'}]`, e); lastErr = performance.now(); }
      }
    }
    renderer.render(scene, camera3d);
    requestAnimationFrame(frame);
  }
  requestAnimationFrame(frame);

  // Expose for the Playwright smoke test + debugging.
  window.__ctx = ctx;
  window.__gameReady = true;
}

try {
  boot();
} catch (e) {
  console.error('[boot] fatal', e);
  // Still flag ready=false so the smoke test reports the real failure.
  window.__bootError = String(e);
}
